# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/162NepVyOFp9Xz8MeXfTJcgUY8mNPn9ig
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, f1_score
import joblib

# 1. Load the dataset
df = pd.read_csv('delivery_delay.csv')

# 2. Separate features (X) and the target variable (y)
X = df.drop(columns=['Delivery_Delay'])
y = df['Delivery_Delay']

# 3. Split the data into training (80%) and testing (20%) sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 4. Initialize and train the Logistic Regression model
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

# 5. Make predictions on the test set
y_pred = model.predict(X_test)

# 6. Evaluate accuracy and precision
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)

print(f"Model Accuracy:  {accuracy:.4f}")
print(f"Model Precision: {precision:.4f}")
print(f"Model recall: {recall:.4f}")
print(f"Model F1 Score: {f1:.4f}")
print(f"Model Confusion Matrix: {cm}")

# 7. Save/Dump the trained model to a .sav file
model_filename = 'delivery_delay_model.sav'
joblib.dump(model, model_filename)
print(f"Model successfully saved to '{model_filename}'")

